// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvfdedo_kxrSvFY_INdV9Ph3KigxIvJnw',
    appId: '1:599331155949:web:6d3b92b3b247ab13ee81e4',
    messagingSenderId: '599331155949',
    projectId: 'hexagon-puzzle-prod',
    authDomain: 'hexagon-puzzle-prod.firebaseapp.com',
    databaseURL: 'https://hexagon-puzzle-prod-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hexagon-puzzle-prod.firebasestorage.app',
    measurementId: 'G-HBLKE4F3KR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAau_Kg-abGomqyT3EAujl8VmQPgUhmI3U',
    appId: '1:599331155949:android:321bcf7d017f2a7cee81e4',
    messagingSenderId: '599331155949',
    projectId: 'hexagon-puzzle-prod',
    databaseURL: 'https://hexagon-puzzle-prod-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hexagon-puzzle-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZpxxumudwoXtj2ja2iUI274tAn1lTUTo',
    appId: '1:599331155949:ios:319666fdce2a48bdee81e4',
    messagingSenderId: '599331155949',
    projectId: 'hexagon-puzzle-prod',
    databaseURL: 'https://hexagon-puzzle-prod-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hexagon-puzzle-prod.firebasestorage.app',
    iosBundleId: 'com.example.sixBallPuzzle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZpxxumudwoXtj2ja2iUI274tAn1lTUTo',
    appId: '1:599331155949:ios:319666fdce2a48bdee81e4',
    messagingSenderId: '599331155949',
    projectId: 'hexagon-puzzle-prod',
    databaseURL: 'https://hexagon-puzzle-prod-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hexagon-puzzle-prod.firebasestorage.app',
    iosBundleId: 'com.example.sixBallPuzzle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvfdedo_kxrSvFY_INdV9Ph3KigxIvJnw',
    appId: '1:599331155949:web:a5ae16d21d90a153ee81e4',
    messagingSenderId: '599331155949',
    projectId: 'hexagon-puzzle-prod',
    authDomain: 'hexagon-puzzle-prod.firebaseapp.com',
    databaseURL: 'https://hexagon-puzzle-prod-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hexagon-puzzle-prod.firebasestorage.app',
    measurementId: 'G-4YBN3QGDJ1',
  );

}