// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpvovicYCjXDgVT3jq0j-p_PedeyqbKgg',
    appId: '1:418193050055:web:4817a2d98e0575dabbb1e2',
    messagingSenderId: '418193050055',
    projectId: 'ballpuzzle-81978',
    authDomain: 'ballpuzzle-81978.firebaseapp.com',
    databaseURL: 'https://ballpuzzle-81978-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ballpuzzle-81978.firebasestorage.app',
    measurementId: 'G-DJKGHSFLNH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPrH7Yd3Dwr3N0d_sqy1XSstAEOkoMLWg',
    appId: '1:418193050055:android:fb82940b1fe21454bbb1e2',
    messagingSenderId: '418193050055',
    projectId: 'ballpuzzle-81978',
    databaseURL: 'https://ballpuzzle-81978-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ballpuzzle-81978.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXE2aUO5F4rPK10Gn5Iosm0XlgiQKUFN0',
    appId: '1:418193050055:ios:8d32cd6af9ac7aefbbb1e2',
    messagingSenderId: '418193050055',
    projectId: 'ballpuzzle-81978',
    databaseURL: 'https://ballpuzzle-81978-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ballpuzzle-81978.firebasestorage.app',
    iosBundleId: 'com.example.sixBallPuzzle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXE2aUO5F4rPK10Gn5Iosm0XlgiQKUFN0',
    appId: '1:418193050055:ios:8d32cd6af9ac7aefbbb1e2',
    messagingSenderId: '418193050055',
    projectId: 'ballpuzzle-81978',
    databaseURL: 'https://ballpuzzle-81978-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ballpuzzle-81978.firebasestorage.app',
    iosBundleId: 'com.example.sixBallPuzzle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpvovicYCjXDgVT3jq0j-p_PedeyqbKgg',
    appId: '1:418193050055:web:aa5f22166b300232bbb1e2',
    messagingSenderId: '418193050055',
    projectId: 'ballpuzzle-81978',
    authDomain: 'ballpuzzle-81978.firebaseapp.com',
    databaseURL: 'https://ballpuzzle-81978-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ballpuzzle-81978.firebasestorage.app',
    measurementId: 'G-15NSB2KG0D',
  );
}
